### ISSUE TITLE
Running substrate-events-listener without a container will not catch events

### ISSUE THREAD

**Issue by hhicks13** [substrate-developer-hub/substrate-events-listener#1]
If I run `npm start` using node v12.6.0 rather than a container, I get the following 
<img width="1468" alt="event-listener-error" src="https://user-images.githubusercontent.com/31278553/61317904-e300e180-a7d1-11e9-8745-81bb58ae5eb3.png">

I **do** receive confirmation from mongodb and substrate that network connection was successful.

The mystery is that the node process does not terminate, so at first it appears to be successful but when I issue transactions on the network, there is **no confirmation** that events are heard by the event-listener app, and the database shows nothing is being added. 

Could this be a versioning issue, or do more specific changes need to made to the `.env` file? I (perhaps wrongfully) assumed that my `.env` configuration was correct when I received confirmation from both substrate and mongodb that connection was successful.

**Comment by gautamdhameja** [comment]
This should be fixed in commit 9cbed9199b2292d7aabc1a22f9bfff0ee393074b. I have removed docker for simplicity. Seems to be working fine after the changes. Closing.
